name: GoogleQuest
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py37_0
  - astor=0.8.0=py37_0
  - boto=2.49.0=py37_0
  - boto3=1.9.234=py_0
  - botocore=1.12.234=py_0
  - bz2file=0.98=py37_1
  - c-ares=1.15.0=h7b6447c_1001
  - docutils=0.15.2=py37_0
  - gensim=3.8.0=py37h962f231_0
  - google-pasta=0.1.8=py_0
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - jmespath=0.9.4=py_0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - libprotobuf=3.10.1=hd408876_0
  - markdown=3.1.1=py37_0
  - nltk=3.4.5=py37_0
  - protobuf=3.10.1=py37he6710b0_0
  - pyyaml=5.1.2=py37h7b6447c_0
  - s3transfer=0.2.1=py37_0
  - smart_open=1.9.0=py_0
  - termcolor=1.1.0=py37_1
  - werkzeug=0.16.0=py_0
  - wrapt=1.11.2=py37h7b6447c_0
  - yaml=0.1.7=h96e3832_1
  - catalogue=0.0.8=py_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37h72c5cf5_0
  - cymem=2.0.3=py37he1b5a44_0
  - cython-blis=0.4.1=py37h516909a_0
  - gast=0.2.2=py_0
  - grpcio=1.23.0=py37he9ae1f9_0
  - idna=2.8=py37_1000
  - murmurhash=1.0.0=py37he1b5a44_0
  - opt_einsum=3.1.0=py_0
  - plac=0.9.6=py_1
  - preshed=3.0.2=py37he1b5a44_1
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.7.1=py37_0
  - requests=2.22.0=py37_1
  - spacy=2.2.3=py37hc9558a2_0
  - srsly=0.2.0=py37he1b5a44_0
  - tensorflow-hub=0.7.0=pyhe1b5a44_0
  - thinc=7.3.0=py37hc9558a2_0
  - tqdm=4.39.0=py_0
  - urllib3=1.25.7=py37_0
  - wasabi=0.4.0=py_0
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.4=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=7.2.0=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.2=py37_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h7b6447c_3
  - pandas=0.25.3=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.2.1=py37h34e0f95_0
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.6=py37h7b6447c_0
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.6.0=py_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py37_0
  - setuptools=42.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - statsmodels=0.10.1=py37hdd07704_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=gpu_py37h768510d_0
  - tensorflow-base=2.0.0=gpu_py37h0ec5d1f_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - tensorflow-gpu=2.0.0=h0d30ee6_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.3.1=py3.7_cuda10.0.130_cudnn7.6.3_0
  - torchvision=0.4.2=py37_cu100
  - pip:
    - blis==0.4.1
    - en-core-web-lg==2.2.5
    - keras==2.2.4
    - torch==1.3.1
prefix: /home/robin/anaconda3/envs/GoogleQuest

